import express from "express";
import cors from "cors";
import OpenAI from "openai";
import { Anthropic } from "@anthropic-ai/sdk";
import { GoogleGenerativeAI } from "@google/generative-ai";

const app = express();
app.use(cors());
app.use(express.json());

app.get("/api/settings", async (req, res) => {
  // In a real app, fetch from DB
  res.json({
    openaiApiKey: process.env.OPENAI_API_KEY,
    photoModel: "dall-e-3",
    captionModel: "gpt-4o-mini"
  });
});

app.post("/api/generate", async (req, res) => {
  const { type, niche, model, provider, apiKey } = req.body;
  
  if (!apiKey) {
    return res.status(400).json({ error: `API Key for ${provider} is required.` });
  }

  try {
    let result;
    if (provider === "openai") {
      const openai = new OpenAI({ apiKey });
      if (type === "text") {
        const response = await openai.chat.completions.create({
          model,
          messages: [{ role: "user", content: `Write a high-quality social media caption about ${niche}. Include relevant hashtags.` }]
        });
        const generatedText = response.choices[0].message.content || "";
        const lines = generatedText.split("\n");
        const hashtags = lines[lines.length - 1].startsWith("#") ? lines.pop()?.split(" ").filter(t => t.startsWith("#")) : [];
        const text = lines.join("\n").trim();
        result = { 
          text: text || `AI Generated Caption for ${niche}`,
          hashtags: hashtags?.length ? hashtags.map(h => h.replace("#", "")) : [niche.toLowerCase(), "trending", "ai"]
        };
      } else {
        const response = await openai.images.generate({
          model: "dall-e-3",
          prompt: `${niche} themed high-quality professional photography, cinematic lighting, ultra-detailed, 8k resolution`,
        });
        result = { url: response.data?.[0]?.url, prompt: `${niche} themed artwork generated by ${model}` };
      }
    } else if (provider === "anthropic") {
      const anthropic = new Anthropic({ apiKey });
      const response = await anthropic.messages.create({
        model: model as any,
        max_tokens: 1024,
        messages: [{ role: "user", content: `Write a high-quality social media caption about ${niche}. Include relevant hashtags.` }]
      });
      const generatedText = response.content[0].type === 'text' ? response.content[0].text : "";
      const lines = generatedText.split("\n");
      const hashtags = lines[lines.length - 1].startsWith("#") ? lines.pop()?.split(" ").filter(t => t.startsWith("#")) : [];
      const text = lines.join("\n").trim();
      result = { 
        text: text || `AI Generated Caption for ${niche}`,
        hashtags: hashtags?.length ? hashtags.map(h => h.replace("#", "")) : [niche.toLowerCase(), "trending", "ai"]
      };
    } else if (provider === "google") {
      const genAI = new GoogleGenerativeAI(apiKey);
      const genModel = genAI.getGenerativeModel({ model: model.includes("pro") ? "gemini-1.5-pro" : "gemini-1.5-flash" });
      const response = await genModel.generateContent(`Write a high-quality social media caption about ${niche}. Include relevant hashtags.`);
      const generatedText = response.response.text();
      const lines = generatedText.split("\n");
      const hashtags = lines[lines.length - 1].startsWith("#") ? lines.pop()?.split(" ").filter(t => t.startsWith("#")) : [];
      const text = lines.join("\n").trim();
      result = { 
        text: text || `AI Generated Caption for ${niche}`,
        hashtags: hashtags?.length ? hashtags.map(h => h.replace("#", "")) : [niche.toLowerCase(), "trending", "ai"]
      };
    }

    res.json(result);
  } catch (error: any) {
    res.status(500).json({ error: error.message });
  }
});

const PORT = process.env.PORT || 5000;
app.listen(PORT, () => console.log(`Secure proxy running on port ${PORT}`));
