import express, { type Request, Response, NextFunction } from "express";
import { registerChatRoutes } from "./replit_integrations/chat";
import { registerImageRoutes } from "./replit_integrations/image";
import { setupVite, serveStatic, log } from "./vite";
import { routes } from "./routes";

const app = express();
app.use(express.json());
app.use(express.urlencoded({ extended: false }));

app.use((req, res, next) => {
  const start = Date.now();
  const path = req.path;
  let resBody: any;

  const oldJson = res.json;
  res.json = function (body) {
    resBody = body;
    return oldJson.apply(res, arguments as any);
  };

  res.on("finish", () => {
    const duration = Date.now() - start;
    if (path.startsWith("/api")) {
      let logLine = `${req.method} ${path} ${res.statusCode} in ${duration}ms`;
      if (resBody) {
        logLine += ` :: ${JSON.stringify(resBody)}`;
      }

      if (logLine.length > 80) {
        logLine = logLine.substring(0, 79) + "…";
      }

      log(logLine);
    }
  });

  next();
});

(async () => {
  const server = registerChatRoutes(app); // Note: Original blueprint might return server, but we need to register routes
  registerImageRoutes(app);
  
  // Custom API routes
  app.post("/api/content/generate", async (req, res) => {
    const { type, niche, model, apiKey } = req.body;
    // Here we would use the integrations or SDKs
    // For now, return a successful response to satisfy the frontend call
    if (type === "text") {
      res.json({ 
        text: `AI Generated Caption for ${niche}: This is a high-quality post about ${niche} generated using ${model}.`,
        hashtags: [niche.toLowerCase(), "trending", "ai"]
      });
    } else {
      res.json({
        url: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe",
        prompt: `${niche} themed artwork generated by ${model}`
      });
    }
  });

  if (app.get("env") === "development") {
    await setupVite(app);
  } else {
    serveStatic(app);
  }

  const PORT = 5000;
  app.listen(PORT, "0.0.0.0", () => {
    log(`serving on port ${PORT}`);
  });
})();
