import type { Express } from "express";
import type { Server } from "http";
import { storage } from "./storage";
import { api } from "@shared/routes";
import { registerChatRoutes } from "./replit_integrations/chat";
import { registerImageRoutes } from "./replit_integrations/image";
import { openai } from "./replit_integrations/image/client";

export async function registerRoutes(httpServer: Server, app: Express): Promise<Server> {
  registerChatRoutes(app);
  registerImageRoutes(app);

  app.get(api.settings.get.path, async (req, res) => {
    const s = await storage.getSettings();
    res.json(s || {});
  });

  app.post(api.settings.update.path, async (req, res) => {
    const s = await storage.updateSettings(req.body);
    res.json(s);
  });

  app.get(api.limits.get.path, async (req, res) => {
    const l = await storage.getLimits();
    res.json(l || { textLimit: 100, imageLimit: 50, videoLimit: 10, textUsed: 0, imageUsed: 0, videoUsed: 0 });
  });

  app.post(api.limits.update.path, async (req, res) => {
    const l = await storage.updateLimits(req.body);
    res.json(l);
  });

  app.get(api.workflows.list.path, async (req, res) => {
    const w = await storage.getWorkflows();
    res.json(w);
  });

  app.post(api.workflows.toggle.path, async (req, res) => {
    const w = await storage.updateWorkflow(Number(req.params.id), req.body.enabled);
    res.json(w);
  });

  app.get(api.content.list.path, async (req, res) => {
    const c = await storage.getContent();
    res.json(c);
  });

  app.delete("/api/content/:id", async (req, res) => {
    await storage.deleteContent(Number(req.params.id));
    res.sendStatus(204);
  });

  // Facebook Posting Helper
  const postToFacebook = async (pageId: string, accessToken: string, message: string, imageUrl?: string) => {
    const baseUrl = `https://graph.facebook.com/v18.0/${pageId}/photos`;
    const params = new URLSearchParams({
      message,
      access_token: accessToken,
    });
    if (imageUrl) params.append("url", imageUrl);

    const response = await fetch(`${baseUrl}?${params.toString()}`, { method: "POST" });
    if (!response.ok) {
      const error = await response.json();
      throw new Error(error.error?.message || "Facebook API error");
    }
    return response.json();
  };

  app.post("/api/content/:id/post", async (req, res) => {
    try {
      const [item] = await db.select().from(content).where(eq(content.id, Number(req.params.id)));
      if (!item) return res.status(404).json({ error: "Content not found" });

      const settings = await storage.getSettings();
      if (!settings?.fbAccessToken || !settings?.fbPageId) {
        return res.status(400).json({ error: "Facebook configuration missing" });
      }

      const data = item.data as any;
      const result = await postToFacebook(
        settings.fbPageId,
        settings.fbAccessToken,
        data.text || data.prompt || "Generated by AI",
        data.url
      );

      res.json({ success: true, result });
    } catch (error: any) {
      console.error("Posting failed:", error);
      res.status(500).json({ error: error.message });
    }
  });

  app.post(api.content.generate.path, async (req, res) => {
    const { type } = req.body;
    const settings = await storage.getSettings();
    const niche = settings?.niche || "General";
    
    let generatedData = {};
    
    try {
      if (type === "text") {
        const response = await openai.chat.completions.create({
          model: settings?.captionModel || "gpt-5",
          messages: [{ role: "user", content: `Write a social media post for the ${niche} niche.` }],
        });
        generatedData = { text: response.choices[0].message.content };
      } else if (type === "image") {
        const response = await openai.images.generate({
          model: "gpt-image-1",
          prompt: `A professional image for a social media post in the ${niche} niche.`,
        });
        generatedData = { url: response.data[0].url, prompt: response.data[0].revised_prompt };
      }

      const c = await storage.createContent({ 
        type, 
        data: generatedData, 
        status: "ready" 
      });

      const limits = await storage.getLimits();
      if (limits) {
        await storage.updateLimits({
          textUsed: type === "text" ? (limits.textUsed || 0) + 1 : limits.textUsed,
          imageUsed: type === "image" ? (limits.imageUsed || 0) + 1 : limits.imageUsed,
        });
      }

      res.json(c);
    } catch (error: any) {
      console.error("AI Generation failed:", error);
      res.status(500).json({ error: error.message });
    }
  });

  return httpServer;
}
