import { VercelRequest, VercelResponse } from '@vercel/node';
import OpenAI from 'openai';
import { Anthropic } from '@anthropic-ai/sdk';
import { GoogleGenerativeAI } from '@google/generative-ai';

export default async function handler(req: VercelRequest, res: VercelResponse) {
  // Only allow POST requests
  if (req.method !== 'POST') {
    return res.status(405).json({ error: 'Method not allowed' });
  }

  const { type, niche, model, provider, apiKey } = req.body;
  
  // Validate required fields
  if (!type || !niche || !model || !provider || !apiKey) {
    return res.status(400).json({ 
      error: 'Missing required fields',
      required: ['type', 'niche', 'model', 'provider', 'apiKey']
    });
  }

  try {
    let result;

    if (provider === "openai") {
      const openai = new OpenAI({ apiKey });
      
      if (type === "text") {
        const response = await openai.chat.completions.create({
          model,
          messages: [{ 
            role: "user", 
            content: `Write a high-quality social media caption about ${niche}. Include relevant hashtags at the end.` 
          }]
        });
        
        const generatedText = response.choices[0].message.content || "";
        const lines = generatedText.split("\n");
        const lastLine = lines[lines.length - 1];
        const hashtags = lastLine.startsWith("#") 
          ? lines.pop()?.split(" ").filter(t => t.startsWith("#")).map(h => h.replace("#", "")) 
          : [];
        const text = lines.join("\n").trim();
        
        result = { 
          text: text || `AI Generated Caption for ${niche}`,
          hashtags: hashtags?.length ? hashtags : [niche.toLowerCase(), "trending", "ai"]
        };
      } else if (type === "image") {
        const response = await openai.images.generate({
          model: "dall-e-3",
          prompt: `${niche} themed high-quality professional photography, cinematic lighting, ultra-detailed, 8k resolution`,
        });
        result = { 
          url: response.data?.[0]?.url, 
          prompt: `${niche} themed artwork generated by ${model}` 
        };
      }
    } 
    else if (provider === "anthropic") {
      const anthropic = new Anthropic({ apiKey });
      const response = await anthropic.messages.create({
        model: model as any,
        max_tokens: 1024,
        messages: [{ 
          role: "user", 
          content: `Write a high-quality social media caption about ${niche}. Include relevant hashtags at the end.` 
        }]
      });
      
      const generatedText = response.content[0].type === 'text' ? response.content[0].text : "";
      const lines = generatedText.split("\n");
      const lastLine = lines[lines.length - 1];
      const hashtags = lastLine.startsWith("#") 
        ? lines.pop()?.split(" ").filter(t => t.startsWith("#")).map(h => h.replace("#", "")) 
        : [];
      const text = lines.join("\n").trim();
      
      result = { 
        text: text || `AI Generated Caption for ${niche}`,
        hashtags: hashtags?.length ? hashtags : [niche.toLowerCase(), "trending", "ai"]
      };
    } 
    else if (provider === "google") {
      const genAI = new GoogleGenerativeAI(apiKey);
      const genModel = genAI.getGenerativeModel({ 
        model: model.includes("pro") ? "gemini-1.5-pro" : "gemini-1.5-flash" 
      });
      
      const response = await genModel.generateContent(
        `Write a high-quality social media caption about ${niche}. Include relevant hashtags at the end.`
      );
      
      const generatedText = response.response.text();
      const lines = generatedText.split("\n");
      const lastLine = lines[lines.length - 1];
      const hashtags = lastLine.startsWith("#") 
        ? lines.pop()?.split(" ").filter(t => t.startsWith("#")).map(h => h.replace("#", "")) 
        : [];
      const text = lines.join("\n").trim();
      
      result = { 
        text: text || `AI Generated Caption for ${niche}`,
        hashtags: hashtags?.length ? hashtags : [niche.toLowerCase(), "trending", "ai"]
      };
    } else {
      return res.status(400).json({ error: `Unknown provider: ${provider}` });
    }

    return res.status(200).json(result);
    
  } catch (error: any) {
    console.error("Generation error:", error);
    return res.status(500).json({ 
      error: error.message || "Content generation failed",
      provider,
      type
    });
  }
}
