import express from "express";
import path from "path";
import { fileURLToPath } from "url";
import OpenAI from "openai";
import { Anthropic } from "@anthropic-ai/sdk";
import { GoogleGenerativeAI } from "@google/generative-ai";
import cors from "cors";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const app = express();
app.use(cors());
app.use(express.json());

// API Routes
app.post("/api/content/generate", async (req, res) => {
  const { type, niche, model, apiKey } = req.body;
  if (!apiKey) return res.status(400).json({ error: "API Key required" });

  try {
    if (type === "text") {
      const prompt = `Write a high-quality social media caption about ${niche}. Include relevant hashtags. Make it engaging and professional.`;
      let generatedText = "";
      
      if (model.includes("gpt")) {
        const openai = new OpenAI({ apiKey });
        const response = await openai.chat.completions.create({
          model, messages: [{ role: "user", content: prompt }]
        });
        generatedText = response.choices[0]?.message?.content || "";
      } else if (model.includes("claude")) {
        const anthropic = new Anthropic({ apiKey });
        const response = await anthropic.messages.create({
          model, max_tokens: 1024, messages: [{ role: "user", content: prompt }]
        });
        generatedText = response.content[0].type === 'text' ? response.content[0].text : "";
      } else if (model.includes("gemini")) {
        const genAI = new GoogleGenerativeAI(apiKey);
        const genModel = genAI.getGenerativeModel({ model: model.includes("pro") ? "gemini-1.5-pro" : "gemini-1.5-flash" });
        const result = await genModel.generateContent(prompt);
        generatedText = result.response.text();
      }

      const lines = generatedText.split("\n");
      const hashtags = lines[lines.length - 1].startsWith("#") ? lines.pop()?.split(" ").filter(t => t.startsWith("#")) : [];
      const text = lines.join("\n").trim();

      res.json({ 
        text: text || `AI Generated Caption for ${niche}`,
        hashtags: hashtags?.length ? hashtags.map(h => h.replace("#", "")) : [niche.toLowerCase(), "trending", "ai"]
      });
    } else {
      let imageUrl = "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe";
      if (model.includes("gpt")) {
         const openai = new OpenAI({ apiKey });
         const response = await openai.images.generate({
           model: "dall-e-3",
           prompt: `${niche} themed high-quality professional photography, cinematic lighting, ultra-detailed, 8k resolution`,
           n: 1,
           size: "1024x1024",
         });
         imageUrl = response.data?.[0]?.url || imageUrl;
      }
      
      res.json({
        url: imageUrl,
        prompt: `${niche} themed artwork generated by ${model}`
      });
    }
  } catch (error: any) {
    console.error("AI Generation Error:", error);
    res.status(500).json({ error: error.message });
  }
});

// Serve static files from "dist"
const distPath = path.join(process.cwd(), "dist");
app.use(express.static(distPath));
app.get("*", (req, res) => {
  const indexPath = path.join(distPath, "index.html");
  res.sendFile(indexPath);
});

export default app;
